services:
  coco-salvaje-integraciones:
    image: integraciones-api:staging
    container_name: integraciones-api-staging
    ports:
      - "8001:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - coco-network

networks:
  coco-network:
    external: true