services:
  integraciones-api:
    image: integraciones-api:staging
    container_name: integraciones-api-staging
    user: "1001:1001"
    ports:
      - "8001:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - coco-network
    volumes:
      - ./logs:/app/logs

networks:
  coco-network:
    external: true